os: linux
language: python

python:
  - 2.7
  - 3.4
  - 3.6

addons:
  apt:
    packages:
      - db-util
      - rpm

matrix:
  include:
    # workaround for https://github.com/travis-ci/travis-ci/issues/9815
    - python: 3.7
      dist: xenial
      sudo: true
    # workaround for https://github.com/travis-ci/travis-ci/issues/2312
    - os: osx
      language: generic
      name: "Python: 2.7"
      env: PYTHON_VERSION=2.7.14
    - os: osx
      language: generic
      name: "Python: 3.4"
      env: PYTHON_VERSION=3.4.8
    - os: osx
      language: generic
      name: "Python: 3.6"
      env: PYTHON_VERSION=3.6.3
    - os: osx
      language: generic
      name: "Python: 3.7"
      env: PYTHON_VERSION=3.7.0
    # black formatting check
    - name: "Black formatting"
      python: 3.6
      install: pip install black
      script: black --check .
    - name: "Pyre typechecking"
      python: 3.6
      install: pip install pyre-check
      script: scripts/run_pyre_venv.sh

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update

    # setup python
    brew outdated pyenv || brew upgrade pyenv
    pyenv install "$PYTHON_VERSION"
    eval "$(pyenv init -)"
    pyenv global "$PYTHON_VERSION"

    # setup rpm
    brew install rpm
    sudo mkdir -p /var/lib/rpm
  fi

script:
  - python setup.py test
